---
title: "Appendix: Reparameterized SGLMM (Spatial Generalized Linear Mixed Model): A Review"
author: "Frances Lin"
output: pdf_document
---

## Load packages

```{r}
library(ngspatial)
library(here)
library(tidyverse)
```

## Read data

```{r}
data(infant)
```

## Preprocess data

```{r}
infant$low_weight <- infant$low_weight / infant$births
attach(infant)
Z <- deaths
X <- cbind(1, low_weight, black, hispanic, gini, affluence, stability)
```

```{r}
dim(infant)
```

```{r}
data(A)
```


## Fit the model

```{r}
set.seed(123456)
start.time <- Sys.time()
fit <- sparse.sglmm(Z ~ X - 1 + offset(log(births)), 
                    family = poisson, 
                    A = A,
                    tune = list(sigma.s = 0.02), verbose = TRUE)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```

Time difference of $52.47736$ mins

```{r}
sparse_summary <- summary(fit)
sparse_summary 
```

```{r}
#sparse_summary$coef
coef <- fit$coef
coef
```

```{r}
dic <- fit$dic
dic
```

```{r}
# summary does not work
write_rds(coef, here("results", "coef.rds"))
write_rds(dic, here("results", "dic.rds"))
```

