---
title: "Reparameterized SGLMM (Spatial Generalized Linear Mixed Model): A Review"
author: "Frances Lin"
date: "June 2022"
output: pdf_document
header-includes: \usepackage{setspace}\onehalfspacing
---

## 1. Introduction 

The SGLMM (spatial generalized linear mixed model) is a hierarchical model that introduces spatial dependence through a GMRF (Gaussian Markov random field) (Besag et al., 1991). The SGLMM was initially proposed for prediction for count data. It has later been applied to estimation and prediction for other types of data (e.g. binary) and found applications in many fields (e.g. ecology, geology, epidemiology, image analysis, and forestry). 

The SGLMM has been the dominant model for areal data because of its flexible hierarchical specification, the availability of the software `WinBUGS` for data analysis (Lunn et al., 2000) and various theoretical and computational advantages over the competitive model named automodel. However, SGLMMs suffer from two major shortcomings: i) variance inflation due to spatial confounding and ii) computational challenges posed by high dimensional latent variables (random effects). 

On the other hand, while another model named RHS model seeks to alleviate confounding by introducing synthetic predictors that are orthogonal to the fixed-effects predictors (Reich et al., 2006), failing to account for the underlying graph, the RHS model can result in random-effects structure with negative spatial dependence (i.e. repulsion) that is not typically applied in practice. 

A sparse, reparameterized model that is able to alleviate confounding, and, at the same time, include patterns of positive spatial dependence (i.e. attraction) while excluding patterns of repulsion is proposed. Other methods have been proposed (Higdon, 2002; Cressie & Johannesson, 2008; Banerjee et al., 2008; Furrer et al., 2006; Rue & Tjelmeland, 2002), but these methods focus on dimension reduction for spatial point-referenced models. The proposed model is thus considered one of the first dimension reduction techniques for spatial areal models. 


## 2. Traditional SGLMM (Spatial Generalized Linear Mixed Model) 

### Undirected graphs

Let 
$$
G = (V, E)
$$ 
be an undirected, labelled graph, where $V = \{1, 2,...,n \}$ is a set of vertices (nodes) and $E = \{ i,j \}$ is a set of edges, where $i, j \in V,$ $i \neq j$. Each vertex $v$ represents an area of interest and each edge $e$ represents the proximity of areas $i$ and $j$. The graph $G$ is represented using an adjacency matrix $A$, which is a $nxn$ matrix with $diag(A) = 0$ and entries $A_{ij} = 1 \{ (i, j) \in E, i \neq j\},$ where $1 (\cdot)$ is an indicator function. That is, if the entry $a_{ij}$ is $=1$, then vertex $v_i$ and $v_j$ are adjacent, and the entry is $=0$, otherwise. 

### The traditional SGLMM

Further let $Z = {(Z_1,...Z_n)}^{T}$ be the random field of interest, where $Z_i$ is the random variable associated with vertex $i$. Then, the first stage of the model is given by 

$$
g({E(Z_i | \beta, W_i)}) = X_i \beta + Wi, \ \ \ \ \ \ \ \ \ \ (1)
$$
where $g$ is a link function, $X_i$ is the $i$th row of the design matrix $X$, $\beta$ is a $p$-vector of regression parameters and $W_i$ is a spatial random effect associated with vertex $i$. Different types of data require different canonical choices of the link function $g$. For example, for binary spatial data, it is the logit function, for count data, it is the natural logarithm function, and for normal data, it is the identity function (Nelder & Wedderburn, 1972). 

### GMRF prior for the random effects

The field of random effects $W = {(W_1,...,W_n)}^{T}$, through which spatial dependence is incorporated, is assumed to follow an improper GMRF prior or the so-called intrinsic conditionally autoregressive (Besag & Kooperberg, 1995)

$$
p(W|\tau) \propto \tau^{rank(Q)/2} exp(- \frac{\tau} {2} W^T Q W), \ \ \ \ \ \ \ \ (2)
$$
where $\tau$ is a smoothing (precision) parameter and $Q (= Q(\tau)) = diag(A1) - A$ is a precision matrix. The prevision parameter $\tau$ relates to $Q$ in the same way that the covariance parameter $\sigma^2$ relates to $\Sigma$. The precision matrix $Q$ incorporates both dependence and prior uncertainty. That is, $W_i$ and $W_j,$ $i \neq j,$ are independent given their neighbors $iff$ $Q_{ij} = Q_{ji} = 0$ $iff$ $(i,j) \notin E$, and uncertainty about $W_i$ is inversely proportional to the degree of vertex $i$ ($Q_{ii} = A_i1,$ where $A_i$ is the $i$th row of $A$). 

For spatial data over a continuous domain, i.e. point-referenced data or geostatistical data, a SGLMM can be formulated by replacing the GMRF with a GP (Gaussian process) (Diggle et al., 1998; De Oliveira, 2000; Christensen & Waagepetersen, 2002). In addition, since prior (2) is improper ($Q$ is singular), the SGLMM is restricted to a Bayesian or restricted maximum likelihood (REML) analysis. This paper considers Bayesian analysis. 


## 3. Spatial confounding 

### The automodel 

The automodel, SGLMM's closest competitor, is a Markov random-field model that incorporates dependence directly and is defined as 

$$
g({E(Z_i | \beta, \eta, Z_{-i})}) = X_i \beta + \eta \sum_{(i,j) \in E} Z^*_j, \ \ \ \ \ \ \ \ \ \ (3)
$$
where $g$ is a (canonical) link function, $Z_{-i}$ is the field excluding the $i$th observation, and $\eta$ is the dependence parameter ($\eta > 0$ implies attraction; $\eta < 0$ implies repulsion). For the centred automodel, $Z^*_j = Z_j - \mu_j$, where $\mu_j$ is the independence expectation of $Z_j$ (i.e. $\mu_j = E(Z_j | \beta, \eta = 0) = g^{-1} (X_j \beta)$). For the uncentred automodel, $Z^*_j = Z_j$. 

The sum term $\sum_{(i,j) \in E} Z^*_j$ is called the autocovariate, and it is considered as a synthetic predictor since it uses the observations or observations along with the regression component $X\beta$ of the model. The autocovariate of the centred automodel makes the dependence parameter easily interpretable ($\eta$ captures the relativity of an observation to its neighbours, conditional on the hypothesized regression component). On the other hand, the autocovariate of the uncentred automodel not only poses conceptual challenge but also shows spatial confounding. That is, the uncentred autocovariate is difficult to interpret, and $\beta$ and $\eta$ also tend to be strongly correlated. 

### The RHS model 

The traditional SGLMM can also shown to be confounded. More specifically, introduction of the random effects can inflate the variance of the posterior distribution of $\beta$. This is because the traditional model contains predictors that are collinear with $X$, and this collinearity causes the variance inflation (Reich et al., 2006). 

Consider $P$ be a projection onto $C(X)$

$$
P = X {(X^T X)}^{-1} X^T
$$
and let $P^{\bot}$ be the projection onto $C(X)$'s complement such that $P^{\bot} = I - P$, then equation (1) can be rewritten as 

$$
g({E(Z_i | \beta, W_i)}) = X_i \beta + K_i \gamma + L_i \delta, 
$$
where $K$ and $L$ are orthogonal bases for $C(X)$ and $C(X)^{\bot}$ respectively and $\gamma$ and $\delta$ are random coefficients. $K$ and $X$ now share the same column space, and this is the source of the spatial confounding. 

Setting $\gamma = 0$, the first stage of the RHS model is given by 

$$
g({E(Z_i | \beta, \delta)}) = X_i \beta + L_i \delta,
$$

and, compared to equation (2), the prior for the random effects $\delta$ becomes 

$$
p(\delta|\tau) \propto \tau^{(n-p)/2} exp(- \frac{\tau} {2} \delta^T Q_R \delta),
$$
where $Q_R = L^T Q L$. 

The traditional SGLMM and RHZ model both share very similar approach to that of the automodel. The traditional SGLMM model makes use of synthetic predictors $K$ and $L$, and the RHZ model makes use of $L$. 

The traditional SGLMM is analogous to the uncentred automodel since both models include predictors $K$ and the uncentred autocovariate $\sum Z^*_j$, respectively, that lead to spatial confounding. The RHZ model is analogous to the centred automodel since both models are designed to fit only residual structure of the data. 

## 4. Sparse reparameterization of the areal SGLMM

The RHZ model does not allow parsimonious fitting of the residual clustering. Because the geometry corresponding to the projection $P^{\bot}$ fails to account for the underlying graph $G$, the RHZ model permits structure of negative spatial dependence (i.e. repulsion) in the random effects. However, neighboring observation tends to be similar, rather than dissimilar, so patterns of attraction are more useful in practice. The proposed reparameterized model considers an alternative projection that captures the geometry of the models, thus allowing patterns of positive spatial dependence (i.e. attraction). Utilizing the geometry of the models also leads to dimension reduction of the random effects naturally. 

### The reparameterized model

The random effects for the reparameterized model 

i) allow patterns of positive spatial dependence (i.e. attraction) while excluding patterns of repulsion and 

ii) have dimension much smaller than $n$. 

Consider the operator $(I - 11^T/n) A (I - 11^T/n)$ that appears in the numerator (top) of Moran's $I$-statistic 

$$
I(A) = \frac{n} {1^TA1} \frac{Z^T (I - 11^T/n) A (I - 11^T/n) Z} {Z^T (I - 11^T/n) Z},
$$
where $I$ is a $nxn$ identity matrix and $1$ is a $n$-vector of $1$s, and replace $I - 11^T/n$ with $P^{\bot}$, then the resulting operator called the Moran operator for $X$ with respect to $G$, $P^{\bot} A P^{\bot}$, appears in the numerator of the generalized Moran's $I$-statistic 

$$
I_x (A) = \frac{n} {1^TA1} \frac{Z^T P^{\bot} A P^{\bot} Z} {Z^T P^{\bot} Z}.
$$

......


Assume $M$ to be a matrix that contains the first $q \ll n$ eigenvectors of the Moran operator. Further assume $\lambda_q > 0$ since neighboring observations tend to be similar. 

Replace $L$ with $M$ in the RHS model, then the first stage of the reparameterized model is given by 

$$
g({E(Z_i | \beta, \delta_S)}) = X_i \beta + M_i \delta_S,
$$

and the prior for the random effects $\delta_S$ becomes 

$$
p(\delta_S|\tau) \propto \tau^{q/2} exp(- \frac{\tau} {2} \delta_S^T Q_S \delta_S),
$$
where $Q_S = M^T Q M$. 

The sparse, reparameterized SGLMM model is more closely analogous to the centred automodel than it is to the RHZ model. Both the sparse SGLMM model and centred automodel account for $X$ and the underlying graph. 

On the other hand, the RHZ model accounts for $X$ but does not account for the underlying graph. The uncentred automodel does not fit residual structure to $X$ but does account for the underlying graph by including (uncentred) autocovariate that sums the neighbors. 


## 5. Dimension reduction for spatial models




\newpage

## Reference 

[Bolin, D. (2015). *Lecture 5: Intrinsic GMRFs Gaussian Markov random fields.* Personal Collection of D. Bolin, Chalmers University of Technology, Gothenburg Sweden.](http://www.math.chalmers.se/~bodavid/GMRF2015/Lectures/F5slides.pdf)

[Haran, M. (2011). Gaussian random field models for spatial data. Handbook of Markov Chain Monte Carlo, 449-478.](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.210.4099&rep=rep1&type=pdf)

**Hughes, J., & Haran, M. (2013). Dimension reduction and alleviation of confounding for spatial generalized linear mixed models. Journal of the Royal Statistical Society: Series B (Statistical Methodology), 75(1), 139-159.**

